version: 2
jobs:
  build:
    docker:
      - image: node:stretch
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Solidity
          command: 'npm  -g install solc@v0.4.19'
      - run:
          name: Install Truffle
          command: 'npm  -g install truffle@v4.0.6'
      - run:
          name: Truffle Compile
          command: 'cd token && truffle compile'
  analysis:
    docker:
      - image: luongnguyen/oyente:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Analyse Token Contract
          command: 'cd /oyente/oyente && python oyente.py -s ~/repo/token/contracts/Token.sol'
      - run:
          name: Analyse Proxy Contract
          command: 'cd /oyente/oyente && python oyente.py -s ~/repo/token/contracts/Proxy.sol'

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - analysis:
          requires:
            - build
