version: 2
jobs:
  build:
    docker:
      - image: node:stretch
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Solidity
          command: 'npm  -g install solc@v0.4.19'
      - run:
          name: Install Truffle
          command: 'npm  -g install truffle@v4.0.6'
      - run:
          name: Install ganache-cli
          command: 'npm  -g install ganache-cli@6.1.4'
      - run:
          name: Truffle Compile
          command: 'cd token && truffle compile'
      - run:
          name: Truffle test
          command: 'bash .circleci/ci.sh'
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - analysis:
          requires:
            - build
